services:
  - type: web
    name: momentum-swelab-backend
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        fromService:
          type: web
          name: momentum-swelab-backend
          property: port
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REACT_APP_API_URL
        value: https://momentum-swelab-backend.onrender.com

